name: PRs reviews reminder

on:
  schedule:
    # Every weekday every 2 hours during working hours (utc), send notification
    - cron: "0 13-22/2 * * 1-5"
jobs:
  pr-reviews-reminder:
    runs-on: ubuntu-latest
    steps:
    - uses: DavideViolante/pr-reviews-reminder-action@v1.3.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        webhook-url: ${{ secrets.WEBHOOK_URL }}
        provider: 'msteams'